execute:
  - SilverStripe\Headless\GraphQL\ModelLoader
modelConfig:
  DataObject:
    type_formatter: 'SilverStripe\Core\ClassInfo::shortName'
    base_fields:
      ID: ID!
      HashID: String
      TypeAncestry: '[[String]]'
    plugins:
      versioning: false
      inheritance:
        useUnionQueries: false
    operations:
      read:
        plugins:
          filter: true
          readVersion: false
      readOne:
        plugins:
          readVersion: false
