---
Name: silverstripe-headless-routes
After: '#modelascontrollerroutes'
---
SilverStripe\Control\Director:
  rules:
    'hooks': '%$SilverStripe\Headless\Controllers\IncomingWebhookController'
    '': '->admin'
